apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: default
data: 
  # Rest
  POSTGRES_URL: "postgres://postgres:123@user-psql:5432/dev"
  USER_REDIS_URL: "user-redis:6379"
  MATCH_REDIS_URL: "match-redis:6379"
  QUESTION_REDIS_URL: "question-redis:6379"
  BLACKLIST_REDIS_URL: "blacklist-redis:6379"
  KAFKA_URL: "kafka:29092"

  # Socket io
  URI_MATCH_SVC: "http://matching-service:7001"
  CHAT_REDIS_URL: "redis://message-redis:6379"
  COLLAB_REDIS_URL: "redis://document-redis:6379"

  # Frontend
  CHOKIDAR_USEPOLLING: "true"
  REACT_APP_BACKEND_URL: "http://192.168.59.107:30080"
