apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: frontend
  
  template:
    metadata:
      name: frontend
      labels: 
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ttraveller7/peerprep-frontend:dev
          imagePullPolicy: Always
          env: 
            - name: CHOKIDAR_USEPOLLING
              value: "true"
            - name: REACT_APP_BACKEND_URL
              value: http://192.168.59.105:30080

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 3000
      nodePort: 30030
  selector:
    app: frontend
  type: NodePort
