apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000

  selector:
    app: user-service

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - name: http
      port: 13704

  selector:
    app: auth-service

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  ports:
    - name: http
      port: 17001

  selector:
    app: question-service

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: matching-service
spec:
  ports:
    - name: http
      port: 7001

  selector:
    app: matching-service

  type: ClusterIP
