apiVersion: v1
kind: Service
metadata:
  name: socketio-matching-service
spec:
  ports:
    - port: 5200

  selector:
    app: socketio-matching-service

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: socketio-chat-service
spec:
  ports:
    - port: 5300

  selector:
    app: socketio-chat-service

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: socketio-collab-service
spec:
  ports:
    - port: 5400

  selector:
    app: socketio-collab-service

  type: ClusterIP
