# Matching

apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketio-matching-service
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: socketio-matching-service
  
  template:
    metadata:
      name: socketio-matching-service
      labels: 
        app: socketio-matching-service
    spec:
      containers:
        - name: socketio-matching-service
          image: ttraveller7/peerprep-socketio-matching-service:dev
          envFrom: 
          - configMapRef: 
              name: global-config
---

# Chat

apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketio-chat-service
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: socketio-chat-service
  
  template:
    metadata:
      name: socketio-chat-service
      labels: 
        app: socketio-chat-service
    spec:
      containers:
        - name: socketio-chat-service
          image: ttraveller7/peerprep-socketio-chat-service:dev
          envFrom: 
          - configMapRef: 
              name: global-config

---

# Collab

apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketio-collab-service
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: socketio-collab-service
  
  template:
    metadata:
      name: socketio-collab-service
      labels: 
        app: socketio-collab-service
    spec:
      containers:
        - name: socketio-collab-service
          image: ttraveller7/peerprep-socketio-collab-service:dev
          envFrom: 
          - configMapRef: 
              name: global-config