# Claim - Kafka

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-kafka
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: slow
  resources: 
    requests:
      storage: 10Gi

---

# Claim - Zookeeper

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-zookeeper
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources: 
    requests:
      storage: 1Gi

---

# Claim - Blacklist Redis

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-blacklist-redis
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources: 
    requests:
      storage: 1Gi

---

# Claim - User Redis

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-user-redis
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources: 
    requests:
      storage: 1Gi

---

# Claim - Match Redis

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-match-redis
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources: 
    requests:
      storage: 1Gi

---

# Claim - Question Redis

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-question-redis
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources: 
    requests:
      storage: 1Gi

---

# Claim - User Psql

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-user-psql
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources: 
    requests:
      storage: 10Gi

---

# Claim - Message

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-message-redis
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources: 
    requests:
      storage: 1Gi

---

# Claim - Document

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-document-redis
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources: 
    requests:
      storage: 1Gi

---

# Storage class - standard

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2

--- 

# Storage class - slow

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: st1
